### ISSUE TITLE
Gulp 4 support?

### ISSUE THREAD

**Issue by Thorium** [htmlhint/gulp-htmlhint-inline#20]
Hi,

When using this component with Gulp 4 (v4.0.2), my NPM complains:

```
npm WARN gulp-htmlhint-inline@0.0.9 requires a peer of gulp@^3.9.1 but none is installed. You must install peer dependencies yourself.
```

**Comment by Thorium** [comment]
I guess it comes from here:
https://github.com/htmlhint/gulp-htmlhint-inline/blob/d398e0ba21861c07769e920d05f2fa205ce258a1/package.json#L34
...but I don't know why it's needed.

**Comment by Kassaila** [comment]
Have an error to.

```
npm ERR! Found: gulp@4.0.2
npm ERR! node_modules/gulp
npm ERR!   dev gulp@"4.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer gulp@"^3.9.1" from gulp-htmlhint-inline@0.0.9
npm ERR! node_modules/gulp-htmlhint-inline
npm ERR!   dev gulp-htmlhint-inline@"*" from the root project
```

```json
{
"devDependencies": {
    "gulp": "^4.0.0",
    "gulp-jshint": "^2.0.3"
  },
  "peerDependencies": {
    "gulp": "^3.9.1"
  }
}
```

This is not valid usage of dependencies.

**Comment by Thorium** [comment]
Thanks. Are you able to update npm package https://www.npmjs.com/package/gulp-htmlhint-inline ?

**Comment by coliff** [comment]
I'll try to help get that done, but I don't have npm publish access/controls. Only @thedaviddias does. Thanks for the PR though. I'll update you with any news :-)

**Comment by Thorium** [comment]
Any news to update the npm? If the package is "locked", could this be released with some separate name to npm?
